TRUNCATE TABLE `modulos`;
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('2', 'SAMSUNG', 'J1 ACE', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('3', 'SAMSUNG', 'J2 CORE', '52250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('4', 'SAMSUNG', 'J4-J400', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('5', 'SAMSUNG', 'J4 CORE / J4 PLUS / J6 PLUS', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('6', 'SAMSUNG', 'J5 PRIME', '49750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('7', 'SAMSUNG', 'J700', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('8', 'SAMSUNG', 'J7 NEO', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('9', 'SAMSUNG', 'J710 2016 OLED', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('10', 'SAMSUNG', 'J7 PRIME', '52250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('11', 'SAMSUNG', 'J7 PRO OLED', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('12', 'SAMSUNG', 'A01 M', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('13', 'SAMSUNG', 'A01 CORE', '49750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('14', 'SAMSUNG', 'A01 CORE CON MARCO', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('15', 'SAMSUNG', 'A02 A022', '54750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('16', 'SAMSUNG', 'A02 UNIV', '52250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('17', 'SAMSUNG', 'A02 A127F', '52250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('18', 'SAMSUNG', 'A02s PREMIUM', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('19', 'SAMSUNG', 'A02s CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('20', 'SAMSUNG', 'A03 / A03s PREMIUM', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('21', 'SAMSUNG', 'A03s CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('22', 'SAMSUNG', 'A03 CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('23', 'SAMSUNG', 'A03 CORE', '49750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('24', 'SAMSUNG', 'A03 CORE CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('25', 'SAMSUNG', 'A04', '52250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('26', 'SAMSUNG', 'A04 PREMIUM', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('27', 'SAMSUNG', 'A04 CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('28', 'SAMSUNG', 'A04 S PREMIUM', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('29', 'SAMSUNG', 'A04 S CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('30', 'SAMSUNG', 'A04 E PREMIUM', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('31', 'SAMSUNG', 'A04 E CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('32', 'SAMSUNG', 'A05 ACTUALIZADO', '74750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('33', 'SAMSUNG', 'A05 CON MARCO', '94750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('34', 'SAMSUNG', 'A05s CON MARCO SERVICE PACK', '102250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('35', 'SAMSUNG', 'A06 PREMIUM', '82250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('36', 'SAMSUNG', 'A06 CON MARCO', '107250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('37', 'SAMSUNG', 'A07', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('38', 'SAMSUNG', 'A10 PREMIUM', '52250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('39', 'SAMSUNG', 'A10 CON MARCO', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('40', 'SAMSUNG', 'A10S', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('41', 'SAMSUNG', 'A10S CON MARCO', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('42', 'SAMSUNG', 'A10S CON MARCO SERVICE PACK', '72250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('43', 'SAMSUNG', 'A11', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('44', 'SAMSUNG', 'A11 CON MARCO', '74750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('45', 'SAMSUNG', 'M12-A02 M127F', '52250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('46', 'SAMSUNG', 'A12 VERSION A032', '52250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('47', 'SAMSUNG', 'A12 VERSION A125 UNIVERSAL', '49750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('48', 'SAMSUNG', 'A12 VERSION A125 UNIVERSAL CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('49', 'SAMSUNG', 'A13 4G UNIVERSAL', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('50', 'SAMSUNG', 'A13 5G (A136)', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('51', 'SAMSUNG', 'A13 CON MARCO', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('52', 'SAMSUNG', 'A14 4G (A145)', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('53', 'SAMSUNG', 'A14 5G ( A146B) FLEX NEGRO', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('54', 'SAMSUNG', 'A15 CON MARCO', '177250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('55', 'SAMSUNG', 'A16 OLED', '249750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('56', 'SAMSUNG', 'A16 4G OLED CON MARCO', '279750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('57', 'SAMSUNG', 'A17 OLED CON MARCO', '304750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('58', 'SAMSUNG', 'M20', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('59', 'SAMSUNG', 'A20 OLED', '112250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('60', 'SAMSUNG', 'A20 OLED CON MARCO', '127250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('61', 'SAMSUNG', 'A20S', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('62', 'SAMSUNG', 'A20S CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('63', 'SAMSUNG', 'A21S PREMIUM', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('64', 'SAMSUNG', 'A21S CON MARCO', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('65', 'SAMSUNG', 'A22 4G CON MARCO', '127250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('66', 'SAMSUNG', 'A22 5G', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('67', 'SAMSUNG', 'A22 5G CON MARCO', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('68', 'SAMSUNG', 'M23 M236', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('69', 'SAMSUNG', 'A23 (A235)', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('70', 'SAMSUNG', 'A23 5G (A236)', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('71', 'SAMSUNG', 'A23 (M336)', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('72', 'SAMSUNG', 'A23 CON MARCO ( A235 )', '82250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('73', 'SAMSUNG', 'A23 CON MARCO ( M336 )', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('74', 'SAMSUNG', 'A24 CON MARCO', '157250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('75', 'SAMSUNG', 'A25 CON MARCO', '192250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('76', 'SAMSUNG', 'A30 OLED CON MARCO', '114750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('77', 'SAMSUNG', 'A30S', '112250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('78', 'SAMSUNG', 'A30S CON MARCO', '127250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('79', 'SAMSUNG', 'A31 OLED CON MARCO', '132250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('80', 'SAMSUNG', 'A32 4G OLED CON MARCO', '139750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('81', 'SAMSUNG', 'A32 5G', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('82', 'SAMSUNG', 'A33 5G OLED CON MARCO', '189750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('83', 'SAMSUNG', 'A34 OLED CON MARCO', '224750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('84', 'SAMSUNG', 'A35 OLED CON MARCO', '224750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('85', 'SAMSUNG', 'A36 OLED CON MARCO', '357250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('86', 'SAMSUNG', 'A50 OLED CON MARCO', '114750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('87', 'SAMSUNG', 'A51 OLED CON MARCO', '147250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('88', 'SAMSUNG', 'A52 / A52s OLED CON MARCO', '159750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('89', 'SAMSUNG', 'A53 OLED CON MARCO', '227250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('90', 'SAMSUNG', 'A54 OLED CON MARCO', '224750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('91', 'SAMSUNG', 'A55 OLED CON MARCO (A556)', '237250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('92', 'SAMSUNG', 'A56 5G OLED CON MARCO', '279750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('93', 'SAMSUNG', 'A70 OLED CON MARCO', '192250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('94', 'SAMSUNG', 'A71 OLED CON MARCO', '212250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('95', 'SAMSUNG', 'A72 OLED CON MARCO', '219750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('96', 'SAMSUNG', 'A7 2017 (A720) OLED', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('97', 'SAMSUNG', 'S20 FE OLED CON MARCO (G780) )', '217250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('98', 'SAMSUNG', 'S21 FE OLED CON MARCO', '424750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('99', 'SAMSUNG', 'S22 ULTRA CON MARCO', '774750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('100', 'SAMSUNG', 'S23 ULTRA CON MARCO', '799750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('101', 'SAMSUNG', 'S24 FE OLED CON MARCO', '649750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('102', 'MOTOROLA', 'C', '39750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('103', 'MOTOROLA', 'C PLUS', '39750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('104', 'MOTOROLA', 'G04 PREMIUM', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('105', 'MOTOROLA', 'G04 CON MARCO', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('106', 'MOTOROLA', 'G05 / E15', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('107', 'MOTOROLA', 'G05 CON MARCO', '124750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('108', 'MOTOROLA', 'G06 / G06 POWER', '82250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('109', 'MOTOROLA', 'G4 PLAY CON MARCO', '54750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('110', 'MOTOROLA', 'G5', '37250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('111', 'MOTOROLA', 'G5 PLUS', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('112', 'MOTOROLA', 'G5 S PLUS', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('113', 'MOTOROLA', 'G6 PLAY / E5', '49750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('114', 'MOTOROLA', 'G6 PLAY / E5 CON MARCO', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('115', 'MOTOROLA', 'G6 PLUS', '52250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('116', 'MOTOROLA', 'G7', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('117', 'MOTOROLA', 'G7 PLAY', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('118', 'MOTOROLA', 'G7 PLAY CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('119', 'MOTOROLA', 'G7 POWER', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('120', 'MOTOROLA', 'G7 PLUS', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('121', 'MOTOROLA', 'G8', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('122', 'MOTOROLA', 'G8 PLAY / ONE MACRO', '44750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('123', 'MOTOROLA', 'G8 PLAY CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('124', 'MOTOROLA', 'G8 PLUS', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('125', 'MOTOROLA', 'G8 POWER', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('126', 'MOTOROLA', 'G8 POWER LITE', '49750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('127', 'MOTOROLA', 'G8 POWER LITE CON MARCO', '82250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('128', 'MOTOROLA', 'G9 PLAY / E7 PLUS', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('129', 'MOTOROLA', 'G9 PLAY CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('130', 'MOTOROLA', 'G9 POWER', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('131', 'MOTOROLA', 'G9 POWER CON MARCO', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('132', 'MOTOROLA', 'G9 PLUS', '74750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('133', 'MOTOROLA', 'G9 PLUS CON MARCO', '102250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('134', 'MOTOROLA', 'G10', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('135', 'MOTOROLA', 'G13', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('136', 'MOTOROLA', 'G13 CON MARCO', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('137', 'MOTOROLA', 'G14', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('138', 'MOTOROLA', 'G14 CON MARCO', '114750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('139', 'MOTOROLA', 'G15 / G15 POWER', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('140', 'MOTOROLA', 'G15 CON MARCO', '124750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('141', 'MOTOROLA', 'G20', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('142', 'MOTOROLA', 'G20 CON MARCO', '82250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('143', 'MOTOROLA', 'G22 PREMIUM', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('144', 'MOTOROLA', 'G22 CON MARCO', '82250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('145', 'MOTOROLA', 'G23', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('146', 'MOTOROLA', 'G23 CON MARCO', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('147', 'MOTOROLA', 'G24 PREMIUM', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('148', 'MOTOROLA', 'G24 CON MARCO', '94750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('149', 'MOTOROLA', 'G24 POWER PREMIUM', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('150', 'MOTOROLA', 'G24 POWER CON MARCO', '94750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('151', 'MOTOROLA', 'G30', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('152', 'MOTOROLA', 'G30 CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('153', 'MOTOROLA', 'G31 / G41 / G71 PREMIUM', '149750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('154', 'MOTOROLA', 'G31 CON MARCO', '149750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('155', 'MOTOROLA', 'G32 PREMIUM', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('156', 'MOTOROLA', 'G32 CON MARCO', '102250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('157', 'MOTOROLA', 'G34 PREMIUM', '97250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('158', 'MOTOROLA', 'G35', '109750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('159', 'MOTOROLA', 'G42 PREMIUM', '149750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('160', 'MOTOROLA', 'G42 CON MARCO', '154750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('161', 'MOTOROLA', 'G51', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('162', 'MOTOROLA', 'G51 CON MARCO', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('163', 'MOTOROLA', 'G52 / G82 SIN MARCO', '187250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('164', 'MOTOROLA', 'G52 OLED CON MARCO', '214750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('165', 'MOTOROLA', 'G54', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('166', 'MOTOROLA', 'G55', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('167', 'MOTOROLA', 'G56', '114750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('168', 'MOTOROLA', 'G60/G60S', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('169', 'MOTOROLA', 'G60/G60S CON MARCO', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('170', 'MOTOROLA', 'G75', '124750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('171', 'MOTOROLA', 'G82 OLED CON MARCO', '214750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('172', 'MOTOROLA', 'G84', '204750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('173', 'MOTOROLA', 'G85', '304750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('174', 'MOTOROLA', 'G100', '114750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('175', 'MOTOROLA', 'G100 CON MARCO', '149750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('176', 'MOTOROLA', 'G200', '109750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('177', 'MOTOROLA', 'G200 CON MARCO', '142250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('178', 'MOTOROLA', 'E4 PLUS', '39750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('179', 'MOTOROLA', 'E4 PLUS CON MARCO', '42250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('180', 'MOTOROLA', 'E5 / G6 PLAY', '49750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('181', 'MOTOROLA', 'E5 / G6 PLAY CON MARCO', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('182', 'MOTOROLA', 'E5 PLAY', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('183', 'MOTOROLA', 'E5 PLUS', '49750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('184', 'MOTOROLA', 'E6 PLAY CON MARCO', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('185', 'MOTOROLA', 'E6S', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('186', 'MOTOROLA', 'E6S CON MARCO', '79750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('187', 'MOTOROLA', 'E6I', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('188', 'MOTOROLA', 'E6I CON MARCO', '79750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('189', 'MOTOROLA', 'E6 PLUS', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('190', 'MOTOROLA', 'E6 PLUS CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('191', 'MOTOROLA', 'E7 E7I E7 I POWER', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('192', 'MOTOROLA', 'MOTE E7 CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('193', 'MOTOROLA', 'E7 I POWER CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('194', 'MOTOROLA', 'E7 PLUS', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('195', 'MOTOROLA', 'E7 PLUS CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('196', 'MOTOROLA', 'E13', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('197', 'MOTOROLA', 'E13 CON MARCO', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('198', 'MOTOROLA', 'E14 PREMIUM', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('199', 'MOTOROLA', 'E14 CON MARCO', '92250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('200', 'MOTOROLA', 'E15 / G05', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('201', 'MOTOROLA', 'E15 CON MARCO', '124750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('202', 'MOTOROLA', 'E20', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('203', 'MOTOROLA', 'E20 CON MARCO', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('204', 'MOTOROLA', 'E22 / E22i', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('205', 'MOTOROLA', 'E22-E22I CON MARCO', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('206', 'MOTOROLA', 'E32', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('207', 'MOTOROLA', 'E32 CON MARCO', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('208', 'MOTOROLA', 'E40', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('209', 'MOTOROLA', 'E40 CON MARCO', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('210', 'MOTOROLA', 'ONE', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('211', 'MOTOROLA', 'ONE MACRO / G8 PLAY', '44750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('212', 'MOTOROLA', 'ONE FUSION', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('213', 'MOTOROLA', 'ONE HIPER (XT 2027)', '74750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('214', 'MOTOROLA', 'ONE VISION', '177250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('215', 'MOTOROLA', 'ONE ACTION', '177250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('216', 'MOTOROLA', 'EDGE 20 LITE CON MARCO', '214750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('217', 'MOTOROLA', 'EDGE 30 SIN MARCO', '187250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('218', 'MOTOROLA', 'EDGE 30 CON MARCO', '204750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('219', 'MOTOROLA', 'EDGE 30 PRO', '229750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('220', 'MOTOROLA', 'EDGE 30 NEO', '349750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('221', 'MOTOROLA', 'EDGE 30 FUSION', '304750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('222', 'MOTOROLA', 'EDGE 40 PRO', '247250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('223', 'MOTOROLA', 'EDGE 50 FUSION', '304750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('224', 'MOTOROLA', 'EDGE 50 PRO', '374750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('225', 'IPHONE', '6', '47250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('226', 'IPHONE', '6 S', '49750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('227', 'IPHONE', '6 PLUS', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('228', 'IPHONE', '6 S PLUS', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('229', 'IPHONE', '7', '69750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('230', 'IPHONE', '7 PLUS', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('231', 'IPHONE', '8', '72250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('232', 'IPHONE', '8 PLUS', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('233', 'IPHONE', 'X', '114750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('234', 'IPHONE', 'XS', '114750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('235', 'IPHONE', 'XR', '114750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('236', 'IPHONE', 'XS MAX', '149750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('237', 'IPHONE', '11', '117250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('238', 'IPHONE', '11 PRO OLED', '187250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('239', 'IPHONE', '11 PRO MAX', '189750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('240', 'IPHONE', '12 MINI', '177250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('241', 'IPHONE', '12/12 PRO OLED', '192250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('242', 'IPHONE', '12 PRO MAX', '229750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('243', 'IPHONE', '13', '254750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('244', 'IPHONE', '13 PRO', '304750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('245', 'IPHONE', '13 PRO MAX', '364750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('246', 'IPHONE', '14 CAMBIO IC', '309750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('247', 'IPHONE', '14 PRO OLED', '549750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('248', 'IPHONE', '14 PRO MAX', '564750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('249', 'IPHONE', '15 PRO', '724750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('250', 'IPHONE', '15 PRO MAX', '874750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('251', 'LG', 'G5', '42250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('252', 'LG', 'K8 CON MARCO', '52250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('253', 'LG', 'K8 2017', '52250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('254', 'LG', 'K9', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('255', 'LG', 'K9 CON MARCO', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('256', 'LG', 'K10 2017', '54750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('257', 'LG', 'K20 CON MARCO', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('258', 'LG', 'K22', '57250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('259', 'LG', 'K22 CON MARCO', '72250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('260', 'LG', 'K40', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('261', 'LG', 'K40 OLED CON MARCO', '72250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('262', 'LG', 'K40S', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('263', 'LG', 'K40S CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('264', 'LG', 'K41S OLED', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('265', 'LG', 'K41S CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('266', 'LG', 'K42/K52/K62', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('267', 'LG', 'K42 CON MARCO', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('268', 'LG', 'K50 OLED', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('269', 'LG', 'K50 CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('270', 'LG', 'K50s', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('271', 'LG', 'K51s', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('272', 'LG', 'K51S CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('273', 'LG', 'K52 CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('274', 'LG', 'K61', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('275', 'LG', 'K61 CON MARCO', '82250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('276', 'LG', 'Q60', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('277', 'LG', 'Q60 CON MARCO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('278', 'HUAWEI', 'MATE 8', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('279', 'HUAWEI', 'MATE 10 LITE', '72250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('280', 'HUAWEI', 'MATE 20 LITE', '72250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('281', 'HUAWEI', 'P 20 LITE', '72250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('282', 'HUAWEI', 'Y9 2018', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('283', 'NOKIA', '1.3', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('284', 'NOKIA', '2.3', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('285', 'NOKIA', '2.4', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('286', 'NOKIA', '3.1 PLUS', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('287', 'NOKIA', '5.1 PLUS', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('288', 'XIAOMI', 'REDMI A2 (NUEVO)', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('289', 'XIAOMI', 'REDMI A3 (NUEVO)', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('290', 'XIAOMI', 'REDMI A3 PRO', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('291', 'XIAOMI', 'REDMI A5 - POCO C71', '102250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('292', 'XIAOMI', 'REDMI MI A2', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('293', 'XIAOMI', 'REDMI MI A3 INCELL', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('294', 'XIAOMI', 'REDMI 7', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('295', 'XIAOMI', 'REDMI 7A', '62250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('296', 'XIAOMI', 'REDMI 8 / 8A', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('297', 'XIAOMI', 'REDMI 9', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('298', 'XIAOMI', 'REDMI 9 CON MARCO', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('299', 'XIAOMI', 'REDMI 9A / 9C / 10A', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('300', 'XIAOMI', 'REDMI 10', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('301', 'XIAOMI', 'REDMI 10C', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('302', 'XIAOMI', 'REDMI 12', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('303', 'XIAOMI', 'REDMI 12C', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('304', 'XIAOMI', 'REDMI 13C - POCO C65', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('305', 'XIAOMI', 'REDMI 13C CON MARCO', '102250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('306', 'XIAOMI', 'REDMI 14C - POCO C75', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('307', 'XIAOMI', 'REDMI 15C', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('308', 'XIAOMI', 'NOTE 6 PRO', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('309', 'XIAOMI', 'NOTE 7', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('310', 'XIAOMI', 'NOTE 8', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('311', 'XIAOMI', 'NOTE 8 CON MARCO', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('312', 'XIAOMI', 'NOTE 8 PRO', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('313', 'XIAOMI', 'NOTE 8 T', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('314', 'XIAOMI', 'NOTE 9', '74750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('315', 'XIAOMI', 'NOTE 9 S / PRO', '79750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('316', 'XIAOMI', 'NOTE 10 5G', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('317', 'XIAOMI', 'NOTE 10 4G / 10s OLED', '164750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('318', 'XIAOMI', 'NOTE 10 4G / 10s OLED CON MARCO', '182250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('319', 'XIAOMI', 'NOTE 10 PRO CURVO', '139750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('320', 'XIAOMI', 'NOTE 10 PRO / 11 PRO OLED', '159750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('321', 'XIAOMI', 'NOTE 11 FLEX LARGO', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('322', 'XIAOMI', 'NOTE 11 / NOTE 11S / NOTE 12S FLEX CORTO OLED', '162250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('323', 'XIAOMI', 'NOTE 11 FLEX CORTO T20 CON MARCO', '162250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('324', 'XIAOMI', 'NOTE 11 FLEX CORTO OLED CON MARCO', '184750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('325', 'XIAOMI', 'NOTE 12 OLED', '164750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('326', 'XIAOMI', 'NOTE 12 PRO / PRO PLUS OLED', '192250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('327', 'XIAOMI', 'NOTE 13 4G OLED', '199750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('328', 'XIAOMI', 'NOTE 13 5G', '149750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('329', 'XIAOMI', 'NOTE 13 PRO 4G', '187250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('330', 'XIAOMI', 'NOTE 14', '212250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('331', 'XIAOMI', 'MI 8 LITE', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('332', 'XIAOMI', 'MI 9T / MI 9 PRO', '144750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('333', 'XIAOMI', 'MI 11 LITE OLED', '167250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('334', 'XIAOMI', 'POCO M3 / REDMI 9T', '94750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('335', 'XIAOMI', 'POCO M3 PRO', '79750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('336', 'XIAOMI', 'POCO M6 PRO 4G', '187250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('337', 'XIAOMI', 'POCO M6 PRO 5G', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('338', 'XIAOMI', 'POCO X3', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('339', 'XIAOMI', 'POCO X3 PRO', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('340', 'XIAOMI', 'POCO X5', '164750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('341', 'XIAOMI', 'POCO X6 INCELL', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('342', 'ALCATEL', '1 5033', '59750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('343', 'ALCATEL', '1L OPEN', '69750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('344', 'ALCATEL', '1V PLUS / TCL', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('345', 'ALCATEL', '3H PLUS / 5H PLUS', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('346', 'ALCATEL', '3H / 5H', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('347', 'ALCATEL', '3X', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('348', 'ALCATEL', '5X', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('349', 'TCL', 'L9 S', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('350', 'TCL', 'L7 PLUS', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('351', 'TCL', 'L10 LITE', '69750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('352', 'TCL', 'L10 PLUS', '69750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('353', 'TCL', '10 SE', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('354', 'TCL', '20B', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('355', 'TCL', '20Y 20E', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('356', 'TCL', '20SE', '67250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('357', 'TCL', '30SE / 30e / 305 / 305i', '64750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('358', 'TCL', '30 Plus', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('359', 'TCL', '40 SE ACTUALIZADO', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('360', 'TCL', '403', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('361', 'TCL', '405 / 408', '87250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('362', 'TCL', '40 NxtPaper', '104750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('363', 'TCL', '501', '122250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('364', 'TCL', '503', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('365', 'TCL', '505 / 505s', '84750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('366', 'TCL', '50 SE', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('367', 'TCL', '50 5G', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('368', 'ZTE', 'BLADE A5 / BLADE A7', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('369', 'ZTE', 'BLADE A34 / BLADE A54', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('370', 'ZTE', 'BLADE A35 / BLADE A55', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('371', 'ZTE', 'BLADE A36 / BLADE A56 / BLADE A76', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('372', 'ZTE', 'BLADE A51 / BLADE A71', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('373', 'ZTE', 'BLADE A52', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('374', 'ZTE', 'BLADE A53 / BLADE A53 PLUS', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('375', 'ZTE', 'BLADE A72 / BLADE A72s', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('376', 'ZTE', 'BLADE A73 4G', '92250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('377', 'ZTE', 'V40 Design', '97250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('378', 'ZTE', 'V50 Design', '94750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('379', 'ZTE', 'NUBIA NEO 2 - FOCUS PRO 5G', '124750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('380', 'INFINIX', 'SMART 8 CON MARCO', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('381', 'INFINIX', 'GT 20 PRO', '424750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('382', 'INFINIX', 'HOT 20 4G', '99750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('383', 'INFINIX', 'HOT 40 PRO', '119750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('384', 'INFINIX', 'HOT 50 4G', '124750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('385', 'TECNO SPARK', 'GO 2022 / TECNO POP 5 PRO', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('386', 'TECNO SPARK', 'GO 2024 /  20C', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('387', 'TECNO SPARK', '30C', '92250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('388', 'TECNO SPARK', 'POP 7 CON MARCO', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('389', 'TECNO SPARK', 'TECNO POVA 4', '89750');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('390', 'OPPO', 'A3 - A3x - A3 PRO - A5 - A5 PRO - A5i - A5x - A40 - A60 - A80', '77250');
INSERT INTO `modulos` (`id`, `marca`, `modelo`, `precio`) VALUES ('391', 'REALME', '12X - 14X - C63 - C65 - C71 - C73 5G - C75 5G', '77250');
