CREATE TABLE IF NOT EXISTS `repuestos` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `tipo` VARCHAR(255) DEFAULT NULL,
  `marca` VARCHAR(255) DEFAULT NULL,
  `modelo` VARCHAR(255) DEFAULT NULL,
  `precio` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fotos` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `orden_id` INT NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `orden_id` (`orden_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
